export const proseMono = {
  slate: "prose-slate",
  gray: "prose-gray",
  zinc: "prose-zinc",
  neutral: "prose-neutral",
  stone: "prose-stone",
};

export const h1 = {
  sizes: "prose-h1:text-5xl prose-h1:md:text-7xl",
  colors: {
    red: "prose-h1:text-red-600 prose-h1:dark:text-red-400",
    orange: "prose-h1:text-orange-600 prose-h1:dark:text-orange-400",
    amber: "prose-h1:text-amber-600 prose-h1:dark:text-amber-400",
    yellow: "prose-h1:text-yellow-600 prose-h1:dark:text-yellow-400",
    lime: "prose-h1:text-lime-600 prose-h1:dark:text-lime-400",
    green: "prose-h1:text-green-600 prose-h1:dark:text-green-400",
    emerald: "prose-h1:text-emerald-600 prose-h1:dark:text-emerald-400",
    teal: "prose-h1:text-teal-600 prose-h1:dark:text-teal-400",
    cyan: "prose-h1:text-cyan-600 prose-h1:dark:text-cyan-400",
    sky: "prose-h1:text-sky-600 prose-h1:dark:text-sky-400",
    blue: "prose-h1:text-blue-600 prose-h1:dark:text-blue-400",
    indigo: "prose-h1:text-indigo-600 prose-h1:dark:text-indigo-400",
    violet: "prose-h1:text-violet-600 prose-h1:dark:text-violet-400",
    purple: "prose-h1:text-purple-600 prose-h1:dark:text-purple-400",
    fuchsia: "prose-h1:text-fuchsia-600 prose-h1:dark:text-fuchsia-400",
    pink: "prose-h1:text-pink-600 prose-h1:dark:text-pink-400",
    rose: "prose-h1:text-rose-600 prose-h1:dark:text-rose-400",
    slate: "prose-h1:text-slate-600 prose-h1:dark:text-slate-400",
    gray: "prose-h1:text-gray-600 prose-h1:dark:text-gray-400",
    zinc: "prose-h1:text-zinc-600 prose-h1:dark:text-zinc-400",
    neutral: "prose-h1:text-neutral-600 prose-h1:dark:text-neutral-400",
    stone: "prose-h1:text-stone-600 prose-h1:dark:text-stone-400",
  },
};

export const h2 = {
  sizes: "prose-h2:text-2xl prose-h2:font-semibold prose-h2:leading-6",
  colors: {
    red: "prose-h2:text-red-800 prose-h2:dark:text-red-300",
    orange: "prose-h2:text-orange-800 prose-h2:dark:text-orange-300",
    amber: "prose-h2:text-amber-800 prose-h2:dark:text-amber-300",
    yellow: "prose-h2:text-yellow-800 prose-h2:dark:text-yellow-300",
    lime: "prose-h2:text-lime-800 prose-h2:dark:text-lime-300",
    green: "prose-h2:text-green-800 prose-h2:dark:text-green-300",
    emerald: "prose-h2:text-emerald-800 prose-h2:dark:text-emerald-300",
    teal: "prose-h2:text-teal-800 prose-h2:dark:text-teal-300",
    cyan: "prose-h2:text-cyan-800 prose-h2:dark:text-cyan-300",
    sky: "prose-h2:text-sky-800 prose-h2:dark:text-sky-300",
    blue: "prose-h2:text-blue-800 prose-h2:dark:text-blue-300",
    indigo: "prose-h2:text-indigo-800 prose-h2:dark:text-indigo-300",
    violet: "prose-h2:text-violet-800 prose-h2:dark:text-violet-300",
    purple: "prose-h2:text-purple-800 prose-h2:dark:text-purple-300",
    fuchsia: "prose-h2:text-fuchsia-800 prose-h2:dark:text-fuchsia-300",
    pink: "prose-h2:text-pink-800 prose-h2:dark:text-pink-300",
    rose: "prose-h2:text-rose-800 prose-h2:dark:text-rose-300",
    slate: "prose-h2:text-slate-800 prose-h2:dark:text-slate-300",
    gray: "prose-h2:text-gray-800 prose-h2:dark:text-gray-300",
    zinc: "prose-h2:text-zinc-800 prose-h2:dark:text-zinc-300",
    neutral: "prose-h2:text-neutral-800 prose-h2:dark:text-neutral-300",
    stone: "prose-h2:text-stone-800 prose-h2:dark:text-stone-300",
  },
};

export const h3 = {
  sizes: "prose-h3:text-xl prose-h3:font-semibold prose-h3:leading-none",
  colors: {
    red: "prose-h3:text-red-800 prose-h3:dark:text-red-300",
    orange: "prose-h3:text-orange-800 prose-h3:dark:text-orange-300",
    amber: "prose-h3:text-amber-800 prose-h3:dark:text-amber-300",
    yellow: "prose-h3:text-yellow-800 prose-h3:dark:text-yellow-300",
    lime: "prose-h3:text-lime-800 prose-h3:dark:text-lime-300",
    green: "prose-h3:text-green-800 prose-h3:dark:text-green-300",
    emerald: "prose-h3:text-emerald-800 prose-h3:dark:text-emerald-300",
    teal: "prose-h3:text-teal-800 prose-h3:dark:text-teal-300",
    cyan: "prose-h3:text-cyan-800 prose-h3:dark:text-cyan-300",
    sky: "prose-h3:text-sky-800 prose-h3:dark:text-sky-300",
    blue: "prose-h3:text-blue-800 prose-h3:dark:text-blue-300",
    indigo: "prose-h3:text-indigo-800 prose-h3:dark:text-indigo-300",
    violet: "prose-h3:text-violet-800 prose-h3:dark:text-violet-300",
    purple: "prose-h3:text-purple-800 prose-h3:dark:text-purple-300",
    fuchsia: "prose-h3:text-fuchsia-800 prose-h3:dark:text-fuchsia-300",
    pink: "prose-h3:text-pink-800 prose-h3:dark:text-pink-300",
    rose: "prose-h3:text-rose-800 prose-h3:dark:text-rose-300",
    slate: "prose-h3:text-slate-800 prose-h3:dark:text-slate-300",
    gray: "prose-h3:text-gray-800 prose-h3:dark:text-gray-300",
    zinc: "prose-h3:text-zinc-800 prose-h3:dark:text-zinc-300",
    neutral: "prose-h3:text-neutral-800 prose-h3:dark:text-neutral-300",
    stone: "prose-h3:text-stone-800 prose-h3:dark:text-stone-300",
  },
};

export const h4 = {
  sizes: "prose-h4:text-lg prose-h4:font-medium prose-h4:leading-none",
  colors: {
    red: "prose-h4:text-red-800 prose-h4:dark:text-red-300",
    orange: "prose-h4:text-orange-800 prose-h4:dark:text-orange-300",
    amber: "prose-h4:text-amber-800 prose-h4:dark:text-amber-300",
    yellow: "prose-h4:text-yellow-800 prose-h4:dark:text-yellow-300",
    lime: "prose-h4:text-lime-800 prose-h4:dark:text-lime-300",
    green: "prose-h4:text-green-800 prose-h4:dark:text-green-300",
    emerald: "prose-h4:text-emerald-800 prose-h4:dark:text-emerald-300",
    teal: "prose-h4:text-teal-800 prose-h4:dark:text-teal-300",
    cyan: "prose-h4:text-cyan-800 prose-h4:dark:text-cyan-300",
    sky: "prose-h4:text-sky-800 prose-h4:dark:text-sky-300",
    blue: "prose-h4:text-blue-800 prose-h4:dark:text-blue-300",
    indigo: "prose-h4:text-indigo-800 prose-h4:dark:text-indigo-300",
    violet: "prose-h4:text-violet-800 prose-h4:dark:text-violet-300",
    purple: "prose-h4:text-purple-800 prose-h4:dark:text-purple-300",
    fuchsia: "prose-h4:text-fuchsia-800 prose-h4:dark:text-fuchsia-300",
    pink: "prose-h4:text-pink-800 prose-h4:dark:text-pink-300",
    rose: "prose-h4:text-rose-800 prose-h4:dark:text-rose-300",
    slate: "prose-h4:text-slate-800 prose-h4:dark:text-slate-300",
    gray: "prose-h4:text-gray-800 prose-h4:dark:text-gray-300",
    zinc: "prose-h4:text-zinc-800 prose-h4:dark:text-zinc-300",
    neutral: "prose-h4:text-neutral-800 prose-h4:dark:text-neutral-300",
    stone: "prose-h4:text-stone-800 prose-h4:dark:text-stone-300",
  },
};

export const h5 = {
  sizes: "prose-h5:text-base prose-h5:font-medium prose-h5:leading-none",
  colors: {
    red: "prose-h5:text-red-800 prose-h5:dark:text-red-300",
    orange: "prose-h5:text-orange-800 prose-h5:dark:text-orange-300",
    amber: "prose-h5:text-amber-800 prose-h5:dark:text-amber-300",
    yellow: "prose-h5:text-yellow-800 prose-h5:dark:text-yellow-300",
    lime: "prose-h5:text-lime-800 prose-h5:dark:text-lime-300",
    green: "prose-h5:text-green-800 prose-h5:dark:text-green-300",
    emerald: "prose-h5:text-emerald-800 prose-h5:dark:text-emerald-300",
    teal: "prose-h5:text-teal-800 prose-h5:dark:text-teal-300",
    cyan: "prose-h5:text-cyan-800 prose-h5:dark:text-cyan-300",
    sky: "prose-h5:text-sky-800 prose-h5:dark:text-sky-300",
    blue: "prose-h5:text-blue-800 prose-h5:dark:text-blue-300",
    indigo: "prose-h5:text-indigo-800 prose-h5:dark:text-indigo-300",
    violet: "prose-h5:text-violet-800 prose-h5:dark:text-violet-300",
    purple: "prose-h5:text-purple-800 prose-h5:dark:text-purple-300",
    fuchsia: "prose-h5:text-fuchsia-800 prose-h5:dark:text-fuchsia-300",
    pink: "prose-h5:text-pink-800 prose-h5:dark:text-pink-300",
    rose: "prose-h5:text-rose-800 prose-h5:dark:text-rose-300",
    slate: "prose-h5:text-slate-800 prose-h5:dark:text-slate-300",
    gray: "prose-h5:text-gray-800 prose-h5:dark:text-gray-300",
    zinc: "prose-h5:text-zinc-800 prose-h5:dark:text-zinc-300",
    neutral: "prose-h5:text-neutral-800 prose-h5:dark:text-neutral-300",
    stone: "prose-h5:text-stone-800 prose-h5:dark:text-stone-300",
  },
};

export const h6 = {
  sizes: "prose-h6:text-sm prose-h6:font-medium prose-h6:leading-none",
  colors: {
    red: "prose-h6:text-red-800 prose-h6:dark:text-red-300",
    orange: "prose-h6:text-orange-800 prose-h6:dark:text-orange-300",
    amber: "prose-h6:text-amber-800 prose-h6:dark:text-amber-300",
    yellow: "prose-h6:text-yellow-800 prose-h6:dark:text-yellow-300",
    lime: "prose-h6:text-lime-800 prose-h6:dark:text-lime-300",
    green: "prose-h6:text-green-800 prose-h6:dark:text-green-300",
    emerald: "prose-h6:text-emerald-800 prose-h6:dark:text-emerald-300",
    teal: "prose-h6:text-teal-800 prose-h6:dark:text-teal-300",
    cyan: "prose-h6:text-cyan-800 prose-h6:dark:text-cyan-300",
    sky: "prose-h6:text-sky-800 prose-h6:dark:text-sky-300",
    blue: "prose-h6:text-blue-800 prose-h6:dark:text-blue-300",
    indigo: "prose-h6:text-indigo-800 prose-h6:dark:text-indigo-300",
    violet: "prose-h6:text-violet-800 prose-h6:dark:text-violet-300",
    purple: "prose-h6:text-purple-800 prose-h6:dark:text-purple-300",
    fuchsia: "prose-h6:text-fuchsia-800 prose-h6:dark:text-fuchsia-300",
    pink: "prose-h6:text-pink-800 prose-h6:dark:text-pink-300",
    rose: "prose-h6:text-rose-800 prose-h6:dark:text-rose-300",
    slate: "prose-h6:text-slate-800 prose-h6:dark:text-slate-300",
    gray: "prose-h6:text-gray-800 prose-h6:dark:text-gray-300",
    zinc: "prose-h6:text-zinc-800 prose-h6:dark:text-zinc-300",
    neutral: "prose-h6:text-neutral-800 prose-h6:dark:text-neutral-300",
    stone: "prose-h6:text-stone-800 prose-h6:dark:text-stone-300",
  },
};

export const a = {
  sizes: "prose-a:text-sm prose-a:font-normal prose-a:leading-none",
  colors: {
    red: "prose-a:text-red-800 prose-a:dark:text-red-300",
    orange: "prose-a:text-orange-800 prose-a:dark:text-orange-300",
    amber: "prose-a:text-amber-800 prose-a:dark:text-amber-300",
    yellow: "prose-a:text-yellow-800 prose-a:dark:text-yellow-300",
    lime: "prose-a:text-lime-800 prose-a:dark:text-lime-300",
    green: "prose-a:text-green-800 prose-a:dark:text-green-300",
    emerald: "prose-a:text-emerald-800 prose-a:dark:text-emerald-300",
    teal: "prose-a:text-teal-800 prose-a:dark:text-teal-300",
    cyan: "prose-a:text-cyan-800 prose-a:dark:text-cyan-300",
    sky: "prose-a:text-sky-800 prose-a:dark:text-sky-300",
    blue: "prose-a:text-blue-800 prose-a:dark:text-blue-300",
    indigo: "prose-a:text-indigo-800 prose-a:dark:text-indigo-300",
    violet: "prose-a:text-violet-800 prose-a:dark:text-violet-300",
    purple: "prose-a:text-purple-800 prose-a:dark:text-purple-300",
    fuchsia: "prose-a:text-fuchsia-800 prose-a:dark:text-fuchsia-300",
    pink: "prose-a:text-pink-800 prose-a:dark:text-pink-300",
    rose: "prose-a:text-rose-800 prose-a:dark:text-rose-300",
    slate: "prose-a:text-slate-800 prose-a:dark:text-slate-300",
    gray: "prose-a:text-gray-800 prose-a:dark:text-gray-300",
    zinc: "prose-a:text-zinc-800 prose-a:dark:text-zinc-300",
    neutral: "prose-a:text-neutral-800 prose-a:dark:text-neutral-300",
    stone: "prose-a:text-stone-800 prose-a:dark:text-stone-300",
  },
};

export const p = "prose-p:text-base leading-relaxed";

export const codeColor = {
  red: "prose-pre:bg-red-100 prose-code:text-red-800",
  orange: "prose-pre:bg-orange-100 prose-code:text-orange-800",
  amber: "prose-pre:bg-amber-100 prose-code:text-amber-800",
  yellow: "prose-pre:bg-yellow-100 prose-code:text-yellow-800",
  lime: "prose-pre:bg-lime-100 prose-code:text-lime-800",
  green: "prose-pre:bg-green-100 prose-code:text-green-800",
  emerald: "prose-pre:bg-emerald-100 prose-code:text-emerald-800",
  teal: "prose-pre:bg-teal-100 prose-code:text-teal-800",
  cyan: "prose-pre:bg-cyan-100 prose-code:text-cyan-800",
  sky: "prose-pre:bg-sky-100 prose-code:text-sky-800",
  blue: "prose-pre:bg-blue-100 prose-code:text-blue-800",
  indigo: "prose-pre:bg-indigo-100 prose-code:text-indigo-800",
  violet: "prose-pre:bg-violet-100 prose-code:text-violet-800",
  purple: "prose-pre:bg-purple-100 prose-code:text-purple-800",
  fuchsia: "prose-pre:bg-fuchsia-100 prose-code:text-fuchsia-800",
  pink: "prose-pre:bg-pink-100 prose-code:text-pink-800",
  rose: "prose-pre:bg-rose-100 prose-code:text-rose-800",
  slate: "prose-pre:bg-slate-100 prose-code:text-slate-800",
  gray: "prose-pre:bg-gray-100 prose-code:text-gray-800",
  zinc: "prose-pre:bg-zinc-100 prose-code:text-zinc-800",
  neutral: "prose-pre:bg-neutral-100 prose-code:text-neutral-800",
  stone: "prose-pre:bg-stone-100 prose-code:text-stone-800",
};

export const codeColorDark = {
  red: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-red-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-red-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-red-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-red-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-red-300",
  },
  orange: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-orange-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-orange-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-orange-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-orange-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-orange-300",
  },
  amber: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-amber-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-amber-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-amber-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-amber-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-amber-300",
  },
  yellow: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-yellow-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-yellow-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-yellow-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-yellow-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-yellow-300",
  },
  lime: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-lime-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-lime-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-lime-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-lime-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-lime-300",
  },
  green: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-green-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-green-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-green-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-green-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-green-300",
  },
  emerald: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-emerald-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-emerald-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-emerald-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-emerald-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-emerald-300",
  },
  teal: {
    slate: "dark:prose-pre:bg-slate-800 ",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-teal-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-teal-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-teal-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-teal-300",
  },
  cyan: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-cyan-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-cyan-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-cyan-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-cyan-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-cyan-300",
  },
  sky: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-sky-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-sky-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-sky-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-sky-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-sky-300",
  },
  blue: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-blue-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-blue-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-blue-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-blue-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-blue-300",
  },
  indigo: {
    slate: "dark:prose-pre:bg-slate-800 ",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-indigo-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-indigo-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-indigo-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-indigo-300",
  },
  violet: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-violet-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-violet-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-violet-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-violet-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-violet-300",
  },
  purple: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-purple-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-purple-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-purple-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-purple-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-purple-300",
  },
  fuchsia: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-fuchsia-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-fuchsia-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-fuchsia-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-fuchsia-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-fuchsia-300",
  },
  pink: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-pink-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-pink-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-pink-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-pink-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-pink-300",
  },
  rose: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-rose-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-rose-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-rose-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-rose-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-rose-300",
  },
  slate: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-slate-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-slate-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-slate-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-slate-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-slate-300",
  },
  gray: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-gray-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-gray-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-gray-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-gray-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-gray-300",
  },
  zinc: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-zinc-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-zinc-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-zinc-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-zinc-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-zinc-300",
  },
  neutral: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-neutral-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-neutral-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-neutral-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-neutral-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-neutral-300",
  },
  stone: {
    slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-stone-300",
    gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-stone-300",
    zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-stone-300",
    neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-stone-300",
    stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-stone-300",
  },
};

export const codeMonoDark = {
  slate: "dark:prose-pre:bg-slate-800 dark:prose-code:text-slate-300",
  gray: "dark:prose-pre:bg-gray-800 dark:prose-code:text-gray-300",
  zinc: "dark:prose-pre:bg-zinc-800 dark:prose-code:text-zinc-300",
  neutral: "dark:prose-pre:bg-neutral-800 dark:prose-code:text-neutral-300",
  stone: "dark:prose-pre:bg-stone-800 dark:prose-code:text-stone-300",
};
